// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.coltoneshaw.flightaware",
  "name": "FlightAware",
  "description": "FlightAware plugin for tracking flight departures and arrivals",
  "icon_path": "assets/bot_icon.png",
  "version": "0.1.0",
  "min_server_version": "10.7.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "Configure the FlightAware plugin.",
    "footer": "Use this plugin to track and monitor flight departures and arrivals.",
    "settings": null,
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
