// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.coltoneshaw.weather",
  "name": "Weather Bot",
  "description": "Weather plugin for getting current weather and subscribing to weather updates. Creates a bot user named 'Weather Bot' (@weatherbot) to post weather information.",
  "icon_path": "assets/bot.png",
  "version": "0.1.0",
  "min_server_version": "10.7.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "Configure the Weather plugin.",
    "footer": "Use this plugin to get weather data and manage weather subscriptions. The plugin will create a bot user named 'Weather Bot' (@weatherbot) to post weather information.",
    "settings": [
      {
        "key": "tomorrow_api_key",
        "display_name": "Tomorrow.io API Key",
        "type": "text",
        "help_text": "API key for Tomorrow.io weather service",
        "placeholder": "Enter your Tomorrow.io API key",
        "default": "",
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
