apiVersion: 1

datasources:
- name: mattermost
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  password:
  user:
  database: 
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     httpMethod: "POST"
  version: 1
  editable: true